service: zazu-africa-rest-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    ENVIRONMENT: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/todo-table

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3001

functions:
  createItem:
    handler: src/functions/todo.postTodo
    events:
      - http:
          path: /api/todos
          method: post
  deleteItem:
    handler: src/functions/todo.deleteTodo
    events:
      - http:
          path: /api/todos/{todoId}
          method: delete
  getItem:
    handler: src/functions/todo.getTodo
    events:
      - http:
          path: /api/todos/{todoId}
          method: get
  getItems:
    handler: src/functions/todo.getTodos
    events:
      - http:
          path: /api/todos
          method: get
  patchItem:
    handler: src/functions/todo.patchTodo
    events:
      - http:
          path: /api/todos/{todoId}
          method: patch